okx/xlayer-node

jsonrpc/endpoints_eth.go
sequencer/dbmanager.go

- @John
- @Doe
- @-Alice
- @-Bob

add logs for RPC

---

jsonrpc/endpoints_debug_innertx.go
jsonrpc/endpoints_eth_innertx.go

- @John
- @Doe
- @-Alice
- @-Bob

support innertx

---

jsonrpc/config.go
jsonrpc/endpoints_eth.go

- @John
- @Doe
- @-Alice
- @-Bob

pending pool switch

---

cmd/run.go
config/default.go
config/environments/local/local.node.config.toml
config/environments/mainnet/node.config.toml
config/environments/testnet/node.config.toml
pool/config.go
pool/pool.go
pool/pool_test.go
pool/transaction.go
sequencer/dbmanager.go
sequencer/interfaces.go
sequencer/mock_worker.go
sequencer/txtracker.go
sequencer/worker.go

- @John
- @Doe
- @-Alice
- @-Bob

suport free gas of fork5

---

jsonrpc/endpoints_debug.go

- @John
- @Doe
- @-Alice
- @-Bob

sync fix ws debug

---

jsonrpc/endpoints_debug.go
state/runtime/instrumentation/tracers/native/call_flat.go
state/transaction.go
state/types.go

- @John
- @Doe
- @-Alice
- @-Bob

support flatCallTracer  and result limit for trace transaction

---

test/scripts/deploy_sc/main.go

- @John
- @Doe
- @-Alice
- @-Bob

fix make deploy-sc error

---

README.md

- @John
- @Doe
- @-Alice
- @-Bob

fix message too long

---

gasprice/fixed.go
gasprice/follower.go

- @John
- @Doe
- @-Alice
- @-Bob

Add gp info logs

---

jsonrpc/handler.go
jsonrpc/metrics/metrics.go
jsonrpc/server.go

feat(x1): add request method metric

---

config/apollo/apollo.go
config/apollo/common.go
config/apollo/namespace.go
config/apollo/sequencer.go
sequencer/apollo.go
sequencer/finalizer.go

Sequencer support apollo configure
- @John
- @Doe
- @-Alice
- @-Bob

Sequencer support apollo

---

metrics/prometheus.go
sequencer/dbmanager.go
sequencer/finalizer.go
sequencer/interfaces.go
sequencer/metrics/logstatistics.go
sequencer/metrics/logstatisticsimpl.go
sequencer/metrics/metrics.go
synchronizer/metrics/metrics.go
synchronizer/synchronizer.go

- @giskook 
- @zjg555543 
- @-Alice
- @-Bob

add metric for pending tx / trust / virtual / verified batch

---

config/apollo/apollo.go
config/apollo/jsonrpc.go
config/apollo/l2gaspricer.go
config/apollo/namespace.go
config/apollo/sequencer.go

- @John
- @Doe
- @-Alice
- @-Bob

fix apollo skip read from env

---

sequencer/dbmanager.go

- @John
- @Doe
- @-Alice
- @-Bob

Add data streamer logs

---

ethtxmanager/ethtxmanager.go
ethtxmanager/metrics/metrics.go
sequencer/finalizer.go
sequencer/metrics/metrics.go
synchronizer/metrics/metrics.go
synchronizer/synchronizer.go

- @John
- @Doe
- @-Alice
- @-Bob

EthTxManager add metric

---

aggregator/prover/aggregator.pb.go
aggregator/prover/aggregator_grpc.pb.go
cmd/run.go
etherman/etherman.go
jsonrpc/metrics/metrics.go
jsonrpc/metrics/metrics_x1.go
merkletree/hashdb/hashdb.pb.go
merkletree/hashdb/hashdb_grpc.pb.go
sequencer/metrics/metrics.go
sequencer/metrics/metrics_x1.go
sequencesender/sequencesender.go
sequencesender/sequencesender_x1.go
state/runtime/executor/executor.pb.go
state/runtime/executor/executor_grpc.pb.go
state/runtime/instrumentation/tracers/native/gen_callframe_json.go
synchronizer/metrics/metrics.go
synchronizer/metrics/metrics_x1.go

- @John
- @Doe
- @-Alice
- @-Bob

Part7: Final Commit

---

aggregator/prover/aggregator.pb.go
aggregator/prover/aggregator_grpc.pb.go
cmd/run.go
etherman/etherman.go
etherman/etherman_x1.go
jsonrpc/config.go
jsonrpc/metrics/metrics.go
jsonrpc/metrics/metrics_x1.go
jsonrpc/ratelimit.go
merkletree/hashdb/hashdb.pb.go
merkletree/hashdb/hashdb_grpc.pb.go
sequencer/metrics/metrics.go
sequencer/metrics/metrics_x1.go
sequencesender/sequencesender.go
sequencesender/sequencesender_x1.go
state/runtime/executor/executor.pb.go
state/runtime/executor/executor_grpc.pb.go
state/runtime/instrumentation/tracers/native/gen_callframe_json.go
synchronizer/metrics/metrics.go
synchronizer/metrics/metrics_x1.go

- @John
- @Doe
- @-Alice
- @-Bob

Part6: pr#60 ratelimit

---

aggregator/prover/aggregator.pb.go
aggregator/prover/aggregator_grpc.pb.go
cmd/run.go
etherman/etherman.go
etherman/etherman_x1.go
jsonrpc/config.go
jsonrpc/metrics/metrics.go
jsonrpc/metrics/metrics_x1.go
jsonrpc/ratelimit.go
merkletree/hashdb/hashdb.pb.go
merkletree/hashdb/hashdb_grpc.pb.go
metrics/prometheus.go
metrics/prometheus_x1.go
sequencer/dbmanager.go
sequencer/dbmanager_x1.go
sequencer/metrics/logstatisticsimpl.go
sequencer/metrics/logstatisticsimpl_x1.go
sequencer/metrics/metrics.go
sequencer/metrics/metrics_x1.go
sequencesender/sequencesender.go
sequencesender/sequencesender_x1.go
state/runtime/executor/executor.pb.go
state/runtime/executor/executor_grpc.pb.go
state/runtime/instrumentation/tracers/native/gen_callframe_json.go
synchronizer/metrics/metrics.go
synchronizer/metrics/metrics_x1.go

- @John
- @Doe
- @-Alice
- @-Bob

Part5: pr#56 metric

---

jsonrpc/endpoints_eth_innertx.go

- @John
- @Doe
- @-Alice
- @-Bob

Add eth_getBlockInternalTransactions

---

cmd/run.go
config/apollo/l2gaspricer.go
gasprice/apollo.go
gasprice/default.go
gasprice/default_test.go
gasprice/fixed.go
gasprice/fixed_test.go
gasprice/follower.go
gasprice/follower_test.go
gasprice/gaspricesuggester.go

- @John
- @Doe
- @-Alice
- @-Bob

fix support apollo to gaspricer

---

cmd/run.go
etherman/etherman_x1.go
jsonrpc/metrics/metrics_x1.go
pool/pool_test.go
pool/transaction_x1.go
sequencer/dbmanager_x1.go
sequencer/mock_etherman.go
sequencesender/sequencesender.go
sequencesender/sequencesender_x1.go
state/pgstatestorage_x1.go
test/benchmarks/sequencer/common/setup/setup.go

- @John
- @Doe
- @-Alice
- @-Bob

Fix build error

---

config/apollo/apollo.go
go.mod
go.sum

- @John
- @Doe
- @-Alice
- @-Bob

Downgrade agollo

---

config/apollo/apollo.go
config/apollo/namespace.go
config/apollo/pool.go
pool/apollo.go
pool/pool.go

- @John
- @Doe
- @-Alice
- @-Bob

pool support apollo

---

sequencer/apollo_x1.go
sequencer/config.go
sequencer/sequencer.go

- @John
- @Doe
- @-Alice
- @-Bob

add sepciallist

---

metrics/prometheus_x1.go

- @John
- @Doe
- @-Alice
- @-Bob

pr81 fix guage set

---

synchronizer/actions/etrog/processor_l1_update_etrog_sequence.go
synchronizer/actions/forksids.go

- @John
- @Doe
- @-Alice
- @-Bob

Fix fork8 upgrade sync

---

jsonrpc/endpoints_debug_x1.go

- @John
- @Doe
- @-Alice
- @-Bob

Add build internal transaction

---

etherman/mock_etherman.go
ethtxmanager/custodialassets_x1.go
ethtxmanager/custodialassetshttp_x1_test.go
tools/signer/service/service.go
tools/signer/service/type.go

- @John
- @Doe
- @-Alice
- @-Bob

upgrade custodialassets to fork8

---

state/pgstatestorage/pgstatestorage.go

- @John
- @Doe
- @-Alice
- @-Bob

Fix tx index

---

etherman/etherman_x1.go

- @John
- @Doe
- @-Alice
- @-Bob

Split da permit

---

jsonrpc/endpoints_eth_x1.go

- @John
- @Doe
- @-Alice
- @-Bob

Add eth_getBlockInternalTransactionsByIndexAndLimit

---

pool/errors.go

- @John
- @Doe
- @-Alice
- @-Bob

update ErrNoWhitelistedSender msg

---

pool/errors.go

- @John
- @Doe
- @-Alice
- @-Bob

update error msg

---

gasprice/apollo_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

fix dyn set gas price

---

jsonrpc/endpoints_eth_xlayer.go
jsonrpc/mocks/mock_pool_xlayer.go
jsonrpc/types/interfaces.go
pool/pool_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

add eth_minGasPrice RPC

---

event/event.go
sequencer/finalizer.go

- @John
- @Doe
- @-Alice
- @-Bob

stop l1inforoot reorg

---

pool/errors.go
pool/pool.go
pool/pool_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

blocked receiver

---

jsonrpc/server.go
jsonrpc/server_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

Websocket support batch request[v030]

---

state/helper.go
state/transaction.go

- @John
- @Doe
- @-Alice
- @-Bob

Fix hard fork handle

---

sequencer/sequencer.go
sequencer/txsorted_list.go
sequencer/txtracker.go
sequencer/worker.go

- @John
- @Doe
- @-Alice
- @-Bob

use latest gp of sortedlist for claimTx

---

sequencer/finalizer.go

- @John
- @Doe
- @-Alice
- @-Bob

support restart when halt

---

jsonrpc/dynamic_gas_price_xlayer.go
jsonrpc/metrics/metrics.go
jsonrpc/metrics/metrics_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

add dynamic gas price metrics

---

state/interfaces.go
state/mocks/mock_storage_xlayer.go
state/pgstatestorage/batch_xlayer.go
synchronizer/actions/etrog/processor_l1_sequence_batches.go
synchronizer/actions/etrog/processor_l1_sequence_batches_test.go
synchronizer/actions/etrog/processor_l1_sequence_batches_xlayer.go
synchronizer/common/syncinterfaces/mocks/state_full_interface_xlayer.go
synchronizer/common/syncinterfaces/state.go

- @John
- @Doe
- @-Alice
- @-Bob

Fix rpc's batch time

---

sequencer/sequencer.go

- @John
- @Doe
- @-Alice
- @-Bob

fix nil pointer

---

jsonrpc/dynamic_gas_price_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

Modify the congestion conditions of dynamic GP

---

jsonrpc/endpoints_eth.go
state/transaction.go
test/e2e/debug_test.go

- @John
- @Doe
- @-Alice
- @-Bob

add time log

---

pool/pendingstat_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

Fix pending stat check the cost

---

sequencer/finalizer.go

- @John
- @Doe
- @-Alice
- @-Bob

update balance oog

---

jsonrpc/dynamic_gas_price_xlayer.go
jsonrpc/metrics/metrics.go
jsonrpc/metrics/metrics_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

add raw gas price metrics

---

cmd/run.go

- @John
- @Doe
- @-Alice
- @-Bob

Fix seq panic

---

jsonrpc/api_relay_filter_xlayer.go
jsonrpc/api_relay_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

Relay add ban filter

---

pool/pgpoolstorage/pgpoolstorage_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

fix freegas insert db

---

jsonrpc/client/client_xlayer.go

- @John
- @Doe
- @-Alice
- @-Bob

rerun when relay response error

---

jsonrpc/metrics/metrics_xlayer.go
jsonrpc/server.go

- @John
- @Doe
- @-Alice
- @-Bob

Add logs for batch request

---

jsonrpc/endpoints_eth.go

- @John
- @Doe
- @-Alice
- @-Bob

GetFilterChanges return a empty object instead of null when no changes.
